# name: CI-CD Pipeline

# on:
#   push:
#     branches: [main]

# jobs:
#   build-test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       - name: Backend install & test
#         working-directory: backend
#         run: |
#           npm ci
#           npm test || echo "No tests yet"

#       - name: Frontend build
#         working-directory: frontend
#         run: |
#           npm ci
#           npm run build

#       - name: Docker build (validation)
#         run: |
#           docker build -t unimart-backend ./backend
#           docker build -t unimart-frontend ./frontend
